name:                El
version:             0.1.1
github:              "githubuser/El"
license:             BSD3
author:              "Paweł Mazur"
maintainer:          "pawelmazur1@gmail.com"
copyright:           "2020 Paweł Mazur"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Nawia/El#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - parsec
  - regex-tdfa
  - mtl
  - extra
  - monad-loops

executables:
  El-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - El

tests:
  El-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - El
